# Generated by Django 3.0.6 on 2020-05-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20200518_0142'),
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='libro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
    ]
