# Generated by Django 3.0.6 on 2020-05-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_auto_20200518_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
